name: Build And Relase

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --frozen-lockfile --silent

      - name: Build
        run: yarn run build

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          prerelease: false
          files: dist/betternovelpia.user.js