name: Build And Release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/betternovelpia.user.js
            dist/betternovelpia.meta.js
          generate_release_notes: true
